### ISSUE TITLE
自定义关卡

### ISSUE THREAD

**Issue by humandetail** [libondev/memory-block#22]
1. 输入框可以使用非数字输入
<img width="514" alt="image" src="https://github.com/libondev/memory-block/assets/39545747/42f97c4e-f7a3-4a2e-a666-e68d52074d8e">

2. 网格最大数量无限制

**Comment by libondev** [comment]
输入限制已完成，最大网格数量先缓缓，想想怎么做先

**Comment by libondev** [comment]
fixed: https://github.com/libondev/memory-block/pull/30
